//go:build ignore
// +build ignore

package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"strconv"
)

const (
	m         = 80
	blockLen  = 16
	k         = m * blockLen
	blocksLen = 12099  // limit/k + 1
	template  = ":%#x" // or %#b
)

//go:generate go run gen.go

func main() {
	f, err := os.Open("1M-Primes.txt") // unpacked from https://precomputed.org/archives/1M-Primes.zip
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	buf := bytes.NewBuffer([]byte(`// Code generated by go generate gen.go; DO NOT EDIT.`))
	fmt.Fprintln(buf, "\n\npackage bprimes")
	fmt.Fprintf(buf, "\n%s%d%s\n", "type block [", blockLen, "]uint32")
	fmt.Fprintf(buf, "\n%s%d%s\n", "var blocks = [", blocksLen, "]block{")

	var (
		p, i, q, r int
		bitset     uint32
	)
	newLine := true
	sc := bufio.NewScanner(f)

	for s := 0; s < 3; s++ { // skip first three rows
		_ = sc.Scan()
	}
	bitset = 1 << odd2Shift[3] // set bit for 3
	for sc.Scan() {            // start from 7
		p, _ = strconv.Atoi(sc.Text())

		r = p % k
		if r/m != i {
			fmt.Fprintf(buf, strconv.Itoa(i)+template, bitset)

			if p/k == q {
				fmt.Fprint(buf, ",")
			} else {
				fmt.Fprintln(buf, "},")
				newLine = true
			}
			bitset = 0
		}

		q = p / k
		if newLine {
			fmt.Fprint(buf, "\t"+strconv.Itoa(q)+":{")
			newLine = false
		}

		bitset |= (1 << odd2Shift[uint8(p%m)])
		i = r / m
	}

	fmt.Fprintf(buf, strconv.Itoa(i)+template, bitset)
	fmt.Fprintln(buf, "},")
	fmt.Fprintln(buf, "}")

	if err := sc.Err(); err != nil {
		log.Fatal(err)
	}

	out, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatal(err)
	}

	if err := os.WriteFile("blocks.go", out, 0666); err != nil {
		log.Fatal(err)
	}
}

var odd2Shift = map[uint8]uint8{
	1:  0,
	3:  1,
	7:  2,
	9:  3,
	11: 4,
	13: 5,
	17: 6,
	19: 7,
	21: 8,
	23: 9,
	27: 10,
	29: 11,
	31: 12,
	33: 13,
	37: 14,
	39: 15,
	41: 16,
	43: 17,
	47: 18,
	49: 19,
	51: 20,
	53: 21,
	57: 22,
	59: 23,
	61: 24,
	63: 25,
	67: 26,
	69: 27,
	71: 28,
	73: 29,
	77: 30,
	79: 31,
}
